language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - docker pull jonascheng/titan-on-dynamodb
  - pushd docker
  - pushd titan-on-dynamodb
  - docker build -t jonascheng/titan-on-dynamodb -f Dockerfile .
  - popd
  - popd

install:
  - docker-compose up -d

before_script:
  - pip install -r requirements.txt

script:
  - ./run_test.sh

after_script:
  - docker-compose down

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push USER/REPO;
    fi
