language: python
python:
  - "2.7"

# https://docs.travis-ci.com/user/docker/
sudo: required

services:
  - docker

env:
  global:
    - TRAVIS_SECURE_ENV_VARS=true
    - DOCKER_USERNAME=jonascheng
    - secure: "jehyR08v40yiAwaM7usFWYS6egzJgOqFyIe4gjnS0PRbIXQ7yTysiJFomLocqW5TC+692nwU3ksag+0kgnB2+A4ztSLxofJaS+63DalFhvjB4+dO6G9q1n07h8pJ35daG1VIZBPbhh1Uju+40HB1wxgttSy9CZ3xiwhXsljr/4i6eNMxPN+IrxvP0y4O8Zc4F3xxjXhQ+/TIQVSXmGnbw4xtn0hpAajC3ToewBkb6H4ERgjF3Q448TgdEX7E/sYBaayW5E82sGAoqNInYvPXwYO9yewLgX08f9kdwTfYJdSnBPocZ5yaLUYR58peLZdT9DPpoxR6HqXjRWqVB5eEIKzU3zr9dNlKYEINb33LiAdWsLm2QYzEixcZbh4omumg3rgflkLHIhavguFzIDKycdxzQ2/8ZojKPaFGXLqOE3Viec9Kb1CuVQJzMAnfF2SY3pVIKla35F4bDoOWt5YM0YXyFrVsJx5EsOuwBbDOEh7vy1VhkkRpGDmjbTmOKmFJCpAitgFqjgFV/TRPOERJnH+np+JGdtu0OezWidHIShUGMrOqf91NdSRGFVfxUQtddCp4ES37O/uQMFXzq+fDbSbH+0Xgj3dzAiYM5h3XFZJXxebHpFy+W9FvQ3tBpRFQeMAnFvHbMXpABL1VAdFUOW3aokUHKK6+EZg1IhZJvn8="

before_install:
  - docker pull soocii/titan-on-dynamodb
  - docker pull soocii/dynamodb-local
  # build titan
  - pushd docker
  - pushd titan-on-dynamodb
  - docker build --build-arg version=$TRAVIS_BUILD_NUMBER -t soocii/titan-on-dynamodb -f Dockerfile .
  - docker tag soocii/titan-on-dynamodb soocii/titan-on-dynamodb:$TRAVIS_BUILD_NUMBER
  - popd
  - popd
  # build dynamodb-local
  - pushd docker
  - pushd dynamodb-local
  - docker build -t soocii/dynamodb-local -f Dockerfile .
  - popd
  - popd

install:
  - docker-compose up -d

before_script:
  - pip install --no-cache-dir -r requirements.txt

script:
  - pushd tests
  - ./run_test.sh
  - popd

after_script:
  - docker-compose down

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push soocii/titan-on-dynamodb;
    docker push soocii/titan-on-dynamodb:$TRAVIS_BUILD_NUMBER;
    docker push soocii/dynamodb-local;
    fi
