version: '2'

services:
  # local dynamodb container
  dynamodb-local: 
    image: soocii/dynamodb-local
    ports:
      - "8000:8000"

  # titan on dynamodb container
  titan-on-dynamodb: 
    image: soocii/titan-on-dynamodb:titan1.0
    environment:
      - DYNAMODB_HOSTPORT=http://dynamodb-local:8000
      - AWS_ACCESS_KEY_ID=notcheckedlocallybutmustbeprovided
      - AWS_SECRET_ACCESS_KEY=notcheckedlocallybutmustbeprovided
      - GRAPH_NAME=yourdatabasename
      - BASE_URI=http://localhost
    ports:
      - "8182:8182"
      - "8183:8183"
      - "8184:8184"
